title: El sueño de Japón
tagline: Planea, prepárate, y haz realidad tu sueño de mudarte a Japón
tagline2: Este no es un blog de viajes ni de las curiosidades del país nipón. El objetivo del blog es darte las herramientas para crear un camino, una ruta que te lleve a vivir en este maravilloso país. Ir a Japón y quedarse a vivir no es tarea fácil para mucha gente. Por eso necesitas un buen plan, prepararte para ejecutar el plan y estar preparado para las adversidades una vez llegado.


description: Add description here.
cover: /cover4-background.jpg

categories_path: /categories/
tags_path: /tags/
